### ISSUE TITLE
run ROS urdf example but different visualization result 

### ISSUE THREAD

**Issue by Jackiezhou233** [openrr/urdf-viz#256] opened 2024-07-29 09:27 UTC
I run the following example using roslaunch urdf_tutorial display.launch model:=urdf/04-materials.urdf
https://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch#Origins
the visualization is: 
![image](https://github.com/user-attachments/assets/2e958495-347c-4cac-b46f-69f7376e8274)
But when I use the same urdf file through urdf-viz, it turn out to be:
![image](https://github.com/user-attachments/assets/49cbcea4-3418-40b5-9180-dba09c7426a1)

the urdf file is :
![image](https://github.com/user-attachments/assets/77c15060-e349-4371-9654-22245fd81b14)

Why?? the tf transform problem?

**Comment by taiki-e** [comment] 2024-09-03 12:10
This is due to one of the regressions introduced in urdf-rs 0.7 (https://github.com/openrr/urdf-rs/pull/64) that the default value was accidentally changed.

I confirmed that this will be fixed by https://github.com/openrr/urdf-rs/pull/107.

<img width="369" alt="s" src="https://github.com/user-attachments/assets/3a0c710a-73da-46e7-866d-a7a61ab2e275">

**Closed** 2024-09-04 02:05 UTC

**Comment by taiki-e** [comment] 2024-09-12 03:49
Fixed in 0.46.0.
